#pragma once

#ifndef __PIN_USAGE_H__
#define __PIN_USAGE_H__

#define GYPSY_SENSE_PIN 2
#define DEPLOY_SENSE_PIN 3
#define RETRIEVE_SENSE_PIN 4
#define POWER_SENSE_PIN 5

#define RETRIEVE_RELAY_PIN 6
#define DEPLOY_RELAY_PIN 7

#define UP_BUTTON_PIN 14
#define DOWM_BUTTON_PIN 15
#define LEFT_BUTTON_PIN 16
#define RIGHT_BUTTON_PIN 17
#define RETRIEVE_BUTTON_PIN 18
#define DEPLOY_BUTTON_PIN 19

#endif